# CONFIGURATION MODULE
from typing import Optional


GENERATIONS = 200
POPULATION_SIZE = 50
ELITE_KEEP = 25
MACHINE_COUNT = 10
MACHINE_CLEARANCE_M = 1.0

FLOOR_W = 20.0
FLOOR_H = 15.0      

GRID_SIZE = 0.5

MACHINE_SIZES = [(1.0, 1.0) for _ in range(MACHINE_COUNT)]

GRID_COLS = max(1, int(FLOOR_W // GRID_SIZE))
GRID_ROWS = max(1, int(FLOOR_H // GRID_SIZE))

ENTRY_CELL = (0, 0)
EXIT_CELL = (0, 5/GRID_SIZE)

WATER_CELL = (None, None)
GAS_CELL = (None, None)
OTHER_CELL = (None, None)


OVERLAP_PENALTY = 1e9
OUT_OF_BOUNDS_PENALTY = 1e7
DIST_SCALE = 1.0
OBSTACLE_PENALTY = 1e9

BASE_MUTATION_PROB = 0.15
BASE_MUTATION_POS_STD = 1.0 / GRID_SIZE

BASE_MUTATION_ROT_PROB = 0.05
MUTATION_ROT_PROB = BASE_MUTATION_ROT_PROB

BASE_SWAP_PROB = 0.05
SWAP_PROB = BASE_SWAP_PROB

MUTATION_PROB = BASE_MUTATION_PROB
MUTATION_POS_STD = BASE_MUTATION_POS_STD

ROTATIONS = [0, 90, 180, 270]

FLOW_WIDTH_M = 0.25

STOP_REQUESTED = False

OBSTACLES = set()

MACHINE_FIXED = []

MACHINE_LABELS = []
MACHINE_PORTS = []
MACHINE_WORKERS =[]
MACHINE_WATER = []
MACHINE_GAS = []
MACHINE_OTHER = []

MATERIAL_CONNECTIONS = []
WORKER_CONNECTIONS = []
WATER_CONNECTIONS = []
GAS_CONNECTIONS = []
OTHER_CONNECTIONS = []
FACILITY_ENTRY_WEIGHT = 20.0  
FACILITY_EXIT_WEIGHT = 20.0

MODUS = "Rotation"  # "Rotation" oder "Tauschen"
