GENERATIONS = 100
POPULATION_SIZE = 100
ELITE_KEEP = 25
MACHINE_COUNT = 10

FLOOR_W = 20.0
FLOOR_H = 15.0      

GRID_SIZE = 0.25

MACHINE_SIZES = [(1.0, 1.0) for _ in range(MACHINE_COUNT)]

GRID_COLS = max(1, int(FLOOR_W // GRID_SIZE))
GRID_ROWS = max(1, int(FLOOR_H // GRID_SIZE))

ENTRY_CELL = (0, 0)
EXIT_CELL = (0, 5/GRID_SIZE)

OVERLAP_PENALTY = 1e9
OUT_OF_BOUNDS_PENALTY = 1e7
DIST_SCALE = 1.0
OBSTACLE_PENALTY = 1e9

BASE_CROSSOVER_PROB = 0.8
CROSSOVER_PROB = BASE_CROSSOVER_PROB

BASE_MUTATION_PROB = 0.2
BASE_MUTATION_POS_STD: int = round(1.0 / GRID_SIZE)

BASE_MUTATION_ROT_PROB = 0.2
MUTATION_ROT_PROB = BASE_MUTATION_ROT_PROB

BASE_SWAP_PROB = 0.05
SWAP_PROB = BASE_SWAP_PROB

MUTATION_PROB = BASE_MUTATION_PROB
MUTATION_POS_STD: int = BASE_MUTATION_POS_STD

BASE_TELEPORT_PROB = 0.0
TELEPORT_PROB = BASE_TELEPORT_PROB

ROTATIONS = [0, 90, 180, 270]

STOP_REQUESTED = False

UI_UPDATE_EVERY_N = 5

OBSTACLES = set()

MACHINE_FIXED = []

MACHINE_LABELS = []
MACHINE_PORTS = []
MACHINE_WORKERS =[]
MACHINE_UTILITIES = {} # pro angabe: [kind | {"side": dtr, "offser": float}, ...]

MATERIAL_CONNECTIONS = []
WORKER_CONNECTIONS = []

UTILITY_CELLS = {}
UTILITY_CONNECTIONS = {}
UTILITY_WEIGHT = {}

MATERIAL_WEIGHT = 1
WORKER_WEIGHT = 1
All_UTILITY_WEIGHT = 1

MODUS = "Rotation"  # "Rotation" oder "Tauschen"

CREATE_GROUPS = False
GROUPS_FOR_GA = []
GROUP_PHASE = False
GROUP_BY = "Manhatten" # aktuell: Worker, Manhatten möglich